name: Build

on:
  workflow_call:

jobs:
  build:
    name: Build

    runs-on: ubuntu-20.04

    steps:
      - name: Setup
        uses: ./.github/workflows/setup.yml

      - name: Build with Gradle
        run: ./gradlew buildRelease

      - name: Build Release AAB
        id: buildBundle
        run: ./gradlew bundleRelease
