on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          submodules: true

      - name: set up JDK 11
        uses: actions/setup-java@v3.6.0
        with:
          distribution: 'adopt' # See 'Supported distributions' for available options
          java-version: '11'

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: ADD LOCAL PROPERTIES
        run: echo '${{ secrets.LOCAL_PROPERTIES }}' > ./local.properties

      - name: Get version code from build.gradle
        run: echo "VERSION_CODE=$(${{ github.workspace }}/gradlew -q printVersionCode)" >> $GITHUB_ENV

      - name: Get version name from build.gradle
        run: echo "BASE_VERSION_NAME=$(${{ github.workspace }}/gradlew -q printVersionName)" >> $GITHUB_ENV

      - name: Advance version code
        run: echo "VERSION_CODE=$(expr ${{ env.VERSION_CODE }} + 1)" >> $GITHUB_ENV

      - name: Add commit SHA to version name
        run: echo "VERSION_NAME=${{ env.BASE_VERSION_NAME }}-${{ env.VERSION_CODE }}-$(git rev-parse --short ${{ github.sha }})" >> $GITHUB_ENV

      - name: Override version name and code
        uses: chkfung/android-version-actions@v1.2.1
        with:
          gradlePath: app/build.gradle
          versionCode: ${{ env.VERSION_CODE }}
          versionName: ${{ env.VERSION_NAME }}

      - name: Build with Gradle
        run: ./gradlew buildRelease

      - name: Build Release AAB
        id: buildBundle
        run: ./gradlew bundleRelease

      - name: Sign AAB
        id: sign
        uses: r0adkll/sign-android-release@v1
        with:
          releaseDirectory: app/build/outputs/bundle/release
          signingKeyBase64: ${{ secrets.SIGNING_KEY }}
          alias: ${{ secrets.ALIAS }}
          keyStorePassword: ${{ secrets.KEY_STORE_PASSWORD }}
          keyPassword: ${{ secrets.KEY_PASSWORD }}

      - name: Upload AAB
        id: uploadArtifact
        uses: actions/upload-artifact@v3
        with:
          name: app
          path: app/build/outputs/bundle/release/app-release.aab

      - name: Create temp file for storing service_account.json
        id: createTempFile
        run: echo "TMP_SERVICE_ACCOUNT_JSON=$(mktemp)" >> $GITHUB_ENV

      - name: Copy service_account.json
        id: copyServiceAccount
        run: echo '${{ secrets.SERVICE_ACCOUNT_JSON }}' > ${{ env.TMP_SERVICE_ACCOUNT_JSON }}

      - name: Deploy to Play Store
        id: deploy
        uses: r0adkll/upload-google-play@v1.0.19
        with:
          serviceAccountJson: ${{ env.TMP_SERVICE_ACCOUNT_JSON }}
          packageName: io.github.lee0701.mboard
          releaseFiles: app/build/outputs/bundle/release/app-release.aab
          track: internal
          status: completed

      - name: Restore base version name
        uses: chkfung/android-version-actions@v1.2.1
        with:
          gradlePath: app/build.gradle
          versionCode: ${{ env.VERSION_CODE }}
          versionName: ${{ env.BASE_VERSION_NAME }}

      - name: Push new version information
        uses: ko-Kore/publish@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          TASK_NAME: 'Bump version'
          TIMEZONE: 'Asia/Seoul'
          BRANCH_NAME: 'main'
