name: Version

on:
  workflow_call:

jobs:
  inc-version:
    name: Increment Version

    runs-on: ubuntu-20.04

    steps:
      - name: Setup
        uses: ./.github/workflows/setup.yml

      - name: Get version code from build.gradle.kts
        run: echo "VERSION_CODE=$(${{ github.workspace }}/gradlew -q printVersionCode)" >> $GITHUB_ENV

      - name: Increment version code
        run: echo "VERSION_CODE=$(expr ${{ env.VERSION_CODE }} + 1)" >> $GITHUB_ENV

      - name: Generate version name with date and commit SHA
        run: echo "VERSION_NAME=${{ env.VERSION_CODE }}-$(date +%Y%m%d)-$(git rev-parse --short ${{ github.sha }})" >> $GITHUB_ENV

      - name: Override version name and code
        uses: chkfung/android-version-actions@v1.2.1
        with:
          gradlePath: app/build.gradle.kts
          versionCode: ${{ env.VERSION_CODE }}
          versionName: ${{ env.VERSION_NAME }}

      - name: Commit new version
        run: |
          git config --local user.name "Automated Publisher"
          git config --local user.email "actions@users.noreply.github.com"
          git add .
          git commit -m "Bump version to ${{ env.VERSION_CODE }}"
          git tag ${{ env.VERSION_NAME }}

      - name: Push new version information
        run: |
          git push
          git push --tags
